/* Generated By:JavaCC: Do not edit this line. IconLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IconLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int KW_AMP = 6;
  /** RegularExpression Id. */
  int KW_BREAK = 7;
  /** RegularExpression Id. */
  int KW_BY = 8;
  /** RegularExpression Id. */
  int KW_CASE = 9;
  /** RegularExpression Id. */
  int KW_CREATE = 10;
  /** RegularExpression Id. */
  int KW_DEFAULT = 11;
  /** RegularExpression Id. */
  int KW_DO = 12;
  /** RegularExpression Id. */
  int KW_ELSE = 13;
  /** RegularExpression Id. */
  int KW_END = 14;
  /** RegularExpression Id. */
  int KW_EVERY = 15;
  /** RegularExpression Id. */
  int KW_FAIL = 16;
  /** RegularExpression Id. */
  int KW_GLOBAL = 17;
  /** RegularExpression Id. */
  int KW_IF = 18;
  /** RegularExpression Id. */
  int KW_INITIAL = 19;
  /** RegularExpression Id. */
  int KW_INVOCABLE = 20;
  /** RegularExpression Id. */
  int KW_LINK = 21;
  /** RegularExpression Id. */
  int KW_LOCAL = 22;
  /** RegularExpression Id. */
  int KW_NEXT = 23;
  /** RegularExpression Id. */
  int KW_NOT = 24;
  /** RegularExpression Id. */
  int KW_OF = 25;
  /** RegularExpression Id. */
  int KW_PROCEDURE = 26;
  /** RegularExpression Id. */
  int KW_RECORD = 27;
  /** RegularExpression Id. */
  int KW_REPEAT = 28;
  /** RegularExpression Id. */
  int KW_RETURN = 29;
  /** RegularExpression Id. */
  int KW_STATIC = 30;
  /** RegularExpression Id. */
  int KW_SUSPEND = 31;
  /** RegularExpression Id. */
  int KW_THEN = 32;
  /** RegularExpression Id. */
  int KW_TO = 33;
  /** RegularExpression Id. */
  int KW_UNTIL = 34;
  /** RegularExpression Id. */
  int KW_WHILE = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int EXPOENTE = 37;
  /** RegularExpression Id. */
  int REAL_LIT = 38;
  /** RegularExpression Id. */
  int INT_LIT = 39;
  /** RegularExpression Id. */
  int STRING_LIT = 40;
  /** RegularExpression Id. */
  int CSET_LIT = 41;
  /** RegularExpression Id. */
  int OP_SNEQ2_ASGN = 42;
  /** RegularExpression Id. */
  int OP_SEQ2_ASGN = 43;
  /** RegularExpression Id. */
  int OP_LCAT_ASGN = 44;
  /** RegularExpression Id. */
  int OP_CAT_ASGN = 45;
  /** RegularExpression Id. */
  int OP_SGE_ASGN = 46;
  /** RegularExpression Id. */
  int OP_SLE_ASGN = 47;
  /** RegularExpression Id. */
  int OP_SNEQ_ASGN = 48;
  /** RegularExpression Id. */
  int OP_SEQ_ASGN = 49;
  /** RegularExpression Id. */
  int OP_SGT_ASGN = 50;
  /** RegularExpression Id. */
  int OP_SLT_ASGN = 51;
  /** RegularExpression Id. */
  int OP_NEQ_ASGN = 52;
  /** RegularExpression Id. */
  int OP_GE_ASGN = 53;
  /** RegularExpression Id. */
  int OP_LE_ASGN = 54;
  /** RegularExpression Id. */
  int OP_GT_ASGN = 55;
  /** RegularExpression Id. */
  int OP_LT_ASGN = 56;
  /** RegularExpression Id. */
  int OP_EQ_ASGN = 57;
  /** RegularExpression Id. */
  int OP_OR_ASGN = 58;
  /** RegularExpression Id. */
  int OP_QUEST_ASGN = 59;
  /** RegularExpression Id. */
  int OP_BANG_ASGN = 60;
  /** RegularExpression Id. */
  int OP_AT_ASGN = 61;
  /** RegularExpression Id. */
  int OP_POW_ASGN = 62;
  /** RegularExpression Id. */
  int OP_MOD_ASGN = 63;
  /** RegularExpression Id. */
  int OP_DIV_ASGN = 64;
  /** RegularExpression Id. */
  int OP_TIMES_ASGN = 65;
  /** RegularExpression Id. */
  int OP_MINUS_ASGN = 66;
  /** RegularExpression Id. */
  int OP_PLUS_ASGN = 67;
  /** RegularExpression Id. */
  int OP_SWAP = 68;
  /** RegularExpression Id. */
  int OP_ASGN = 69;
  /** RegularExpression Id. */
  int OP_REVSWAP = 70;
  /** RegularExpression Id. */
  int OP_REVASGN = 71;
  /** RegularExpression Id. */
  int OP_SNEQ2 = 72;
  /** RegularExpression Id. */
  int OP_SEQ2 = 73;
  /** RegularExpression Id. */
  int OP_SNEQ = 74;
  /** RegularExpression Id. */
  int OP_SEQ = 75;
  /** RegularExpression Id. */
  int OP_SGE = 76;
  /** RegularExpression Id. */
  int OP_SLE = 77;
  /** RegularExpression Id. */
  int OP_SGT = 78;
  /** RegularExpression Id. */
  int OP_SLT = 79;
  /** RegularExpression Id. */
  int OP_NEQ = 80;
  /** RegularExpression Id. */
  int OP_GE = 81;
  /** RegularExpression Id. */
  int OP_LE = 82;
  /** RegularExpression Id. */
  int OP_GT = 83;
  /** RegularExpression Id. */
  int OP_LT = 84;
  /** RegularExpression Id. */
  int OP_EQ = 85;
  /** RegularExpression Id. */
  int OP_LCAT = 86;
  /** RegularExpression Id. */
  int OP_CAT = 87;
  /** RegularExpression Id. */
  int OP_PLUS = 88;
  /** RegularExpression Id. */
  int OP_MINUS = 89;
  /** RegularExpression Id. */
  int OP_TIMES = 90;
  /** RegularExpression Id. */
  int OP_DIV = 91;
  /** RegularExpression Id. */
  int OP_MOD = 92;
  /** RegularExpression Id. */
  int OP_POW = 93;
  /** RegularExpression Id. */
  int OP_OR = 94;
  /** RegularExpression Id. */
  int OP_AND = 95;
  /** RegularExpression Id. */
  int OP_AT = 96;
  /** RegularExpression Id. */
  int OP_BANG = 97;
  /** RegularExpression Id. */
  int OP_QUEST = 98;
  /** RegularExpression Id. */
  int OP_TILDE = 99;
  /** RegularExpression Id. */
  int OP_BACKSLASH = 100;
  /** RegularExpression Id. */
  int OP_DOT = 101;
  /** RegularExpression Id. */
  int COLON = 102;
  /** RegularExpression Id. */
  int SEMICOLON = 103;
  /** RegularExpression Id. */
  int COMMA = 104;
  /** RegularExpression Id. */
  int LPAREN = 105;
  /** RegularExpression Id. */
  int RPAREN = 106;
  /** RegularExpression Id. */
  int LBRACKET = 107;
  /** RegularExpression Id. */
  int RBRACKET = 108;
  /** RegularExpression Id. */
  int LBRACE = 109;
  /** RegularExpression Id. */
  int RBRACE = 110;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMMENT>",
    "<KW_AMP>",
    "\"break\"",
    "\"by\"",
    "\"case\"",
    "\"create\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"end\"",
    "\"every\"",
    "\"fail\"",
    "\"global\"",
    "\"if\"",
    "\"initial\"",
    "\"invocable\"",
    "\"link\"",
    "\"local\"",
    "\"next\"",
    "\"not\"",
    "\"of\"",
    "\"procedure\"",
    "\"record\"",
    "\"repeat\"",
    "\"return\"",
    "\"static\"",
    "\"suspend\"",
    "\"then\"",
    "\"to\"",
    "\"until\"",
    "\"while\"",
    "<ID>",
    "<EXPOENTE>",
    "<REAL_LIT>",
    "<INT_LIT>",
    "<STRING_LIT>",
    "<CSET_LIT>",
    "\"~===:=\"",
    "\"===:=\"",
    "\"|||:=\"",
    "\"||:=\"",
    "\">>=:=\"",
    "\"<<=:=\"",
    "\"~==:=\"",
    "\"==:=\"",
    "\">>:=\"",
    "\"<<:=\"",
    "\"~=:=\"",
    "\">=:=\"",
    "\"<=:=\"",
    "\">:=\"",
    "\"<:=\"",
    "\"=:=\"",
    "\"|:=\"",
    "\"?:=\"",
    "\"!:=\"",
    "\"@:=\"",
    "\"^:=\"",
    "\"%:=\"",
    "\"/:=\"",
    "\"*:=\"",
    "\"-:=\"",
    "\"+:=\"",
    "\":=:\"",
    "\":=\"",
    "\"<->\"",
    "\"<-\"",
    "\"~===\"",
    "\"===\"",
    "\"~==\"",
    "\"==\"",
    "\">>=\"",
    "\"<<=\"",
    "\">>\"",
    "\"<<\"",
    "\"~=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"|||\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"|\"",
    "\"&\"",
    "\"@\"",
    "\"!\"",
    "\"?\"",
    "\"~\"",
    "\"\\\\\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
  };

}
