/* IconLexerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. IconLexerTokenManager.java */
import java.io.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class IconLexerTokenManager implements IconLexerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active1 & 0x2000000000L) != 0L)
            return 8;
         if ((active0 & 0xfffffff80L) != 0L)
         {
            jjmatchedKind = 36;
            return 6;
         }
         if ((active1 & 0x80000000L) != 0L)
            return 3;
         return -1;
      case 1:
         if ((active0 & 0x202041100L) != 0L)
            return 6;
         if ((active0 & 0xdfdfbee80L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 1;
            }
            return 6;
         }
         return -1;
      case 2:
         if ((active0 & 0x1004000L) != 0L)
            return 6;
         if ((active0 & 0xdfcfbae80L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 2;
            }
            return 6;
         }
         return -1;
      case 3:
         if ((active0 & 0x100a12200L) != 0L)
            return 6;
         if ((active0 & 0xcfc5a8c80L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 3;
            }
            return 6;
         }
         return -1;
      case 4:
         if ((active0 & 0xc00408080L) != 0L)
            return 6;
         if ((active0 & 0xfc1a0c00L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 4;
            return 6;
         }
         return -1;
      case 5:
         if ((active0 & 0x78020400L) != 0L)
            return 6;
         if ((active0 & 0x84180800L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
            return 6;
         }
         return -1;
      case 6:
         if ((active0 & 0x80080800L) != 0L)
            return 6;
         if ((active0 & 0x4100000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 6;
            return 6;
         }
         return -1;
      case 7:
         if ((active0 & 0x4100000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 7;
            return 6;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 97;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 37:
         jjmatchedKind = 92;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x0L);
      case 38:
         return jjStartNfaWithStates_0(0, 95, 3);
      case 40:
         return jjStopAtPos(0, 105);
      case 41:
         return jjStopAtPos(0, 106);
      case 42:
         jjmatchedKind = 90;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2L);
      case 43:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 44:
         return jjStopAtPos(0, 104);
      case 45:
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4L);
      case 46:
         return jjStartNfaWithStates_0(0, 101, 8);
      case 47:
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L);
      case 58:
         jjmatchedKind = 102;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30L);
      case 59:
         return jjStopAtPos(0, 103);
      case 60:
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x148800000000000L, 0x4a0c0L);
      case 61:
         jjmatchedKind = 85;
         return jjMoveStringLiteralDfa1_0(0x202080000000000L, 0xa00L);
      case 62:
         jjmatchedKind = 83;
         return jjMoveStringLiteralDfa1_0(0xa4400000000000L, 0x25000L);
      case 63:
         jjmatchedKind = 98;
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L);
      case 64:
         jjmatchedKind = 96;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 107);
      case 92:
         return jjStopAtPos(0, 100);
      case 93:
         return jjStopAtPos(0, 108);
      case 94:
         jjmatchedKind = 93;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x180L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x600L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1800L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0xe000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1c0000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x600000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1800000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x38000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc0000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x300000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x400000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x800000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 109);
      case 124:
         jjmatchedKind = 94;
         return jjMoveStringLiteralDfa1_0(0x400300000000000L, 0xc00000L);
      case 125:
         return jjStopAtPos(0, 110);
      case 126:
         jjmatchedKind = 99;
         return jjMoveStringLiteralDfa1_0(0x11040000000000L, 0x10500L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40L);
      case 58:
         return jjMoveStringLiteralDfa2_0(active0, 0xff80000000000000L, active1, 0xfL);
      case 60:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8800000000000L, active1, 0x2000L);
      case 61:
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10000L) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x40000L) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x730c0000000000L, active1, 0x710L);
      case 62:
         if ((active1 & 0x4000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4400000000000L, active1, 0x1000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10200L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x38800800L, active1, 0L);
      case 102:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(1, 18, 6);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 25, 6);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x900000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x22000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x400184000L, active1, 0L);
      case 111:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(1, 12, 6);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(1, 33, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x1400000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000480L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L, active1, 0L);
      case 121:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(1, 8, 6);
         break;
      case 124:
         if ((active1 & 0x800000L) != 0L)
         {
            jjmatchedKind = 87;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x300000000000L, active1, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 58:
         if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(2, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0x7e200000000000L, active1, 0L);
      case 61:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(2, 55);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(2, 56);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(2, 57);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(2, 58);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(2, 59);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(2, 60);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(2, 61);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(2, 62);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(2, 63);
         else if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(2, 64);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(2, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(2, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(2, 67);
         else if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1cc0000000000L, active1, 0x100L);
      case 62:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(2, 70);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x8400000L, active1, 0L);
      case 100:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 14, 6);
         break;
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x100008480L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x800090000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4020000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80002200L, active1, 0L);
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 24, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x420000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L, active1, 0L);
      case 124:
         if ((active1 & 0x400000L) != 0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 58:
         return jjMoveStringLiteralDfa4_0(active0, 0x1d80000000000L, active1, 0L);
      case 61:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(3, 45);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(3, 49);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(3, 50);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(3, 51);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(3, 52);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(3, 53);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(3, 54);
         else if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x400c80L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L, active1, 0L);
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 6);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L, active1, 0L);
      case 107:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 6);
         break;
      case 108:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L, active1, 0L);
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 6);
         break;
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x8100000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x40080000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 58:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 61:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(4, 43);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(4, 44);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(4, 46);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(4, 47);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(4, 48);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x10020000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x84000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40080000L);
      case 107:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 7, 6);
         break;
      case 108:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 6);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 6);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x28000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 121:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(5, 42);
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x180000L);
      case 99:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 6);
         break;
      case 100:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 10, 6);
         break;
      case 108:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000L);
      case 116:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 100:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 6);
         break;
      case 108:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 6);
         break;
      case 116:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 6);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(8, 20, 6);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(8, 26, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 37;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 39)
                        kind = 39;
                     { jjCheckNAddStates(0, 6); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAddStates(7, 9); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(10, 12); }
                  else if (curChar == 46)
                     { jjCheckNAdd(8); }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 35)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAdd(1); }
                  }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(1); }
                  break;
               case 2:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if (curChar == 46)
                     { jjCheckNAdd(8); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 10:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(11); }
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAdd(11); }
                  break;
               case 12:
                  if (curChar == 34)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 13:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 15:
                  { jjCheckNAddStates(10, 12); }
                  break;
               case 16:
                  if (curChar == 34 && kind > 40)
                     kind = 40;
                  break;
               case 17:
                  if (curChar == 39)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 18:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 20:
                  { jjCheckNAddStates(7, 9); }
                  break;
               case 21:
                  if (curChar == 39 && kind > 41)
                     kind = 41;
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  { jjCheckNAddStates(0, 6); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 24:
                  if (curChar != 46)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 27:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(28); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAdd(28); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(29, 30); }
                  break;
               case 31:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  { jjCheckNAdd(32); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(33, 34); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  { jjCheckNAdd(36); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(6); }
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(4); }
                  break;
               case 9:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(13, 14); }
                  break;
               case 13:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 14:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  { jjCheckNAddStates(10, 12); }
                  break;
               case 18:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 19:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 20:
                  { jjCheckNAddStates(7, 9); }
                  break;
               case 26:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(15, 16); }
                  break;
               case 30:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(17, 18); }
                  break;
               case 34:
                  if (curChar == 114)
                     { jjCheckNAdd(35); }
                  break;
               case 35:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  { jjCheckNAdd(35); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 13:
               case 15:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 18:
               case 20:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 37 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\142\162\145\141\153", "\142\171", 
"\143\141\163\145", "\143\162\145\141\164\145", "\144\145\146\141\165\154\164", "\144\157", 
"\145\154\163\145", "\145\156\144", "\145\166\145\162\171", "\146\141\151\154", 
"\147\154\157\142\141\154", "\151\146", "\151\156\151\164\151\141\154", 
"\151\156\166\157\143\141\142\154\145", "\154\151\156\153", "\154\157\143\141\154", "\156\145\170\164", 
"\156\157\164", "\157\146", "\160\162\157\143\145\144\165\162\145", 
"\162\145\143\157\162\144", "\162\145\160\145\141\164", "\162\145\164\165\162\156", 
"\163\164\141\164\151\143", "\163\165\163\160\145\156\144", "\164\150\145\156", "\164\157", 
"\165\156\164\151\154", "\167\150\151\154\145", null, null, null, null, null, null, 
"\176\75\75\75\72\75", "\75\75\75\72\75", "\174\174\174\72\75", "\174\174\72\75", "\76\76\75\72\75", 
"\74\74\75\72\75", "\176\75\75\72\75", "\75\75\72\75", "\76\76\72\75", "\74\74\72\75", 
"\176\75\72\75", "\76\75\72\75", "\74\75\72\75", "\76\72\75", "\74\72\75", "\75\72\75", 
"\174\72\75", "\77\72\75", "\41\72\75", "\100\72\75", "\136\72\75", "\45\72\75", 
"\57\72\75", "\52\72\75", "\55\72\75", "\53\72\75", "\72\75\72", "\72\75", "\74\55\76", 
"\74\55", "\176\75\75\75", "\75\75\75", "\176\75\75", "\75\75", "\76\76\75", 
"\74\74\75", "\76\76", "\74\74", "\176\75", "\76\75", "\74\75", "\76", "\74", "\75", 
"\174\174\174", "\174\174", "\53", "\55", "\52", "\57", "\45", "\136", "\174", "\46", "\100", 
"\41", "\77", "\176", "\134", "\56", "\72", "\73", "\54", "\50", "\51", "\133", 
"\135", "\173", "\175", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   23, 24, 29, 30, 33, 34, 36, 18, 19, 21, 13, 14, 16, 10, 11, 27, 
   28, 31, 32, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public IconLexerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public IconLexerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 37; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffdfffffffe1L, 0x7fffffffffffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[37];
    private final int[] jjstateSet = new int[2 * 37];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
