/* IconLexer.java */
/* Generated By:JavaCC: Do not edit this line. IconLexer.java */
import java.io.*;

public class IconLexer implements IconLexerConstants {

    /* ------------------------------------------------------------------ */
    /* Mapeia o número interno do tipo de token para seu nome em maiúsculo */
    /* ------------------------------------------------------------------ */
    static String nomeClasse(int kind) {
        switch (kind) {
            /* Comentário */
            case COMMENT:           return "COMMENT";

            /* &palavras-chave embutidas (&fail, &null, &pos, etc.) */
            case KW_AMP:            return "KW_AMP";

            /* Palavras reservadas */
            case KW_BREAK:          return "KW_BREAK";
            case KW_BY:             return "KW_BY";
            case KW_CASE:           return "KW_CASE";
            case KW_CREATE:         return "KW_CREATE";
            case KW_DEFAULT:        return "KW_DEFAULT";
            case KW_DO:             return "KW_DO";
            case KW_ELSE:           return "KW_ELSE";
            case KW_END:            return "KW_END";
            case KW_EVERY:          return "KW_EVERY";
            case KW_FAIL:           return "KW_FAIL";
            case KW_GLOBAL:         return "KW_GLOBAL";
            case KW_IF:             return "KW_IF";
            case KW_INITIAL:        return "KW_INITIAL";
            case KW_INVOCABLE:      return "KW_INVOCABLE";
            case KW_LINK:           return "KW_LINK";
            case KW_LOCAL:          return "KW_LOCAL";
            case KW_NEXT:           return "KW_NEXT";
            case KW_NOT:            return "KW_NOT";
            case KW_OF:             return "KW_OF";
            case KW_PROCEDURE:      return "KW_PROCEDURE";
            case KW_RECORD:         return "KW_RECORD";
            case KW_REPEAT:         return "KW_REPEAT";
            case KW_RETURN:         return "KW_RETURN";
            case KW_STATIC:         return "KW_STATIC";
            case KW_SUSPEND:        return "KW_SUSPEND";
            case KW_THEN:           return "KW_THEN";
            case KW_TO:             return "KW_TO";
            case KW_UNTIL:          return "KW_UNTIL";
            case KW_WHILE:          return "KW_WHILE";

            /* Identificador */
            case ID:                return "ID";

            /* Literais */
            case INT_LIT:           return "INT_LIT";
            case REAL_LIT:          return "REAL_LIT";
            case STRING_LIT:        return "STRING_LIT";
            case CSET_LIT:          return "CSET_LIT";

            /* ── Operadores augmentados (operador + ":=") ── */
            case OP_SNEQ2_ASGN:     return "OP_SNEQ2_ASGN"; /* ~===:= */
            case OP_SEQ2_ASGN:      return "OP_SEQ2_ASGN";  /* ===:=  */
            case OP_LCAT_ASGN:      return "OP_LCAT_ASGN";  /* |||:=  */
            case OP_SGE_ASGN:       return "OP_SGE_ASGN";   /* >>=:=  */
            case OP_SLE_ASGN:       return "OP_SLE_ASGN";   /* <<=:=  */
            case OP_SNEQ_ASGN:      return "OP_SNEQ_ASGN";  /* ~==:=  */
            case OP_SEQ_ASGN:       return "OP_SEQ_ASGN";   /* ==:=   */
            case OP_CAT_ASGN:       return "OP_CAT_ASGN";   /* ||:=   */
            case OP_SGT_ASGN:       return "OP_SGT_ASGN";   /* >>:=   */
            case OP_SLT_ASGN:       return "OP_SLT_ASGN";   /* <<:=   */
            case OP_NEQ_ASGN:       return "OP_NEQ_ASGN";   /* ~=:=   */
            case OP_GE_ASGN:        return "OP_GE_ASGN";    /* >=:=   */
            case OP_LE_ASGN:        return "OP_LE_ASGN";    /* <=:=   */
            case OP_GT_ASGN:        return "OP_GT_ASGN";    /* >:=    */
            case OP_LT_ASGN:        return "OP_LT_ASGN";    /* <:=    */
            case OP_EQ_ASGN:        return "OP_EQ_ASGN";    /* =:=    */
            case OP_OR_ASGN:        return "OP_OR_ASGN";    /* |:=    */
            case OP_QUEST_ASGN:     return "OP_QUEST_ASGN"; /* ?:=    */
            case OP_BANG_ASGN:      return "OP_BANG_ASGN";  /* !:=    */
            case OP_AT_ASGN:        return "OP_AT_ASGN";    /* @:=    */
            case OP_POW_ASGN:       return "OP_POW_ASGN";   /* ^:=    */
            case OP_MOD_ASGN:       return "OP_MOD_ASGN";   /* %:=    */
            case OP_DIV_ASGN:       return "OP_DIV_ASGN";   /* /:=    */
            case OP_TIMES_ASGN:     return "OP_TIMES_ASGN"; /* *:=    */
            case OP_MINUS_ASGN:     return "OP_MINUS_ASGN"; /* -:=    */
            case OP_PLUS_ASGN:      return "OP_PLUS_ASGN";  /* +:=    */

            /* ── Atribuição / troca ── */
            case OP_SWAP:           return "OP_SWAP";     /* :=:  */
            case OP_ASGN:           return "OP_ASGN";     /* :=   */
            case OP_REVSWAP:        return "OP_REVSWAP";  /* <->  */
            case OP_REVASGN:        return "OP_REVASGN";  /* <-   */

            /* ── Identidade de valor ── */
            case OP_SNEQ2:          return "OP_SNEQ2";  /* ~=== */
            case OP_SEQ2:           return "OP_SEQ2";   /* ===  */

            /* ── Comparação de strings ── */
            case OP_SNEQ:           return "OP_SNEQ";  /* ~== */
            case OP_SEQ:            return "OP_SEQ";   /* ==  */
            case OP_SGE:            return "OP_SGE";   /* >>= */
            case OP_SLE:            return "OP_SLE";   /* <<= */
            case OP_SGT:            return "OP_SGT";   /* >>  */
            case OP_SLT:            return "OP_SLT";   /* <<  */

            /* ── Comparação numérica ── */
            case OP_NEQ:            return "OP_NEQ";  /* ~= */
            case OP_GE:             return "OP_GE";   /* >= */
            case OP_LE:             return "OP_LE";   /* <= */
            case OP_GT:             return "OP_GT";   /* >  */
            case OP_LT:             return "OP_LT";   /* <  */
            case OP_EQ:             return "OP_EQ";   /* =  */

            /* ── Concatenação (string / lista) ── */
            case OP_LCAT:           return "OP_LCAT";  /* ||| */
            case OP_CAT:            return "OP_CAT";   /* ||  */

            /* ── Aritméticos ── */
            case OP_PLUS:           return "OP_PLUS";
            case OP_MINUS:          return "OP_MINUS";
            case OP_TIMES:          return "OP_TIMES";
            case OP_DIV:            return "OP_DIV";
            case OP_MOD:            return "OP_MOD";
            case OP_POW:            return "OP_POW";

            /* ── Demais operadores ── */
            case OP_OR:             return "OP_OR";
            case OP_AND:            return "OP_AND";
            case OP_AT:             return "OP_AT";
            case OP_BANG:           return "OP_BANG";
            case OP_QUEST:          return "OP_QUEST";
            case OP_TILDE:          return "OP_TILDE";
            case OP_BACKSLASH:      return "OP_BACKSLASH";
            case OP_DOT:            return "OP_DOT";

            /* ── Pontuação ── */
            case COLON:             return "COLON";
            case SEMICOLON:         return "SEMICOLON";
            case COMMA:             return "COMMA";
            case LPAREN:            return "LPAREN";
            case RPAREN:            return "RPAREN";
            case LBRACKET:          return "LBRACKET";
            case RBRACKET:          return "RBRACKET";
            case LBRACE:            return "LBRACE";
            case RBRACE:            return "RBRACE";

            default:                return "DESCONHECIDO";
        }
    }

    /* ------------------------------------------------------------------ */
    /* Ponto de entrada                                                     */
    /* ------------------------------------------------------------------ */
    public static void main(String[] args) {
        InputStream entrada = System.in;
        if (args.length > 0) {
            try {
                entrada = new FileInputStream(args[0]);
            } catch (FileNotFoundException e) {
                System.err.println("Erro: arquivo nao encontrado: " + args[0]);
                System.exit(1);
            }
        }

        /*
         * Usamos o TokenManager diretamente – sem chamar produções gramaticais –
         * pois o objetivo é apenas a análise léxica.
         */
        SimpleCharStream fluxo = new SimpleCharStream(entrada, 1, 1);
        IconLexerTokenManager tm = new IconLexerTokenManager(fluxo);

        Token tok;
        try {
            while (true) {
                tok = tm.getNextToken();
                if (tok.kind == EOF) break;
                System.out.println(nomeClasse(tok.kind) + " " + tok.image);
            }
        } catch (TokenMgrError e) {
            System.err.println("Erro lexico: " + e.getMessage());
            System.exit(1);
        }
    }

/* ══════════════════════════════════════════════════════════════════════════
   PRODUÇÃO DUMMY
   O JavaCC exige ao menos uma produção BNF no arquivo.
   Esta produção nunca é chamada pelo main(); usamos o TokenManager direto.
   ══════════════════════════════════════════════════════════════════════════ */
  final public void Dummy() throws ParseException {
    jj_consume_token(0);
}

  /** Generated Token Manager. */
  public IconLexerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	   jj_la1_init_3();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {};
	}
	private static void jj_la1_init_3() {
	   jj_la1_3 = new int[] {};
	}

  /** Constructor with InputStream. */
  public IconLexer(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public IconLexer(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new IconLexerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public IconLexer(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new IconLexerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new IconLexerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Constructor with generated Token Manager. */
  public IconLexer(IconLexerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(IconLexerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[111];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		   if ((jj_la1_3[i] & (1<<j)) != 0) {
			 la1tokens[96+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 111; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
